### ISSUE TITLE
Plugin not updated on Package Control

### ISSUE THREAD

**Issue by rajkiranjoshi** [c3m3gyanesh/p4-syntax-highlighter#4]
Only v1.0.0 is available via Package Control. This version doesn't contain the commits which include support for comments. As per [this page](https://packagecontrol.io/docs/submitting_a_package), we will "need to create a tag each time you want to make a new version available to users." 

Looking forward for a new tag (release).

**Comment by c3m3gyanesh** [comment]
Created a new tag. Let me know if it is still not available.

**Comment by rajkiranjoshi** [comment]
Yes, the new version is available via Package Control now. Thanks!
