### ISSUE TITLE
Removing block comments using toggle shortcut, adds more block comments

### ISSUE THREAD

**Issue by nishantbudhdev** [c3m3gyanesh/p4-syntax-highlighter#5]
Using the shortcut to remove existing block comments causes another layer of block comments to be added instead of removing the existing one.

<img width="325" alt="Toggle block comments error" src="https://user-images.githubusercontent.com/956015/82135852-ed4c9b80-9839-11ea-8e18-024707f8834d.png">

#6 Submitted PR to fix the issue.

**Comment by c3m3gyanesh** [comment]
Thanks @nishantbudhdev for finding this issue with a fix too.
I welcome these fixes and pull request. Feel free to create more of these.
